//
// Created by Ari Reen on 25/12/2020.
//

#ifndef TTGO_T_HIGROW_MODULE_PARAMETER_MANAGEMENT_H
#define TTGO_T_HIGROW_MODULE_PARAMETER_MANAGEMENT_H

void read_configs();

#endif //TTGO_T_HIGROW_MODULE_PARAMETER_MANAGEMENT_H
